# Generated by Django 4.2.7 on 2024-05-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
