# Generated by Django 4.2.7 on 2024-05-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='student',
            new_name='user',
        ),
    ]
