# Generated by Django 4.2.7 on 2024-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_rename_student_certificate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(upload_to='staticfiles/certificates/'),
        ),
    ]
