# Generated by Django 4.2.7 on 2024-05-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='watched_by_users',
            field=models.ManyToManyField(blank=True, to='app.student'),
        ),
        migrations.CreateModel(
            name='StudentCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_weeks', models.ManyToManyField(blank=True, to='app.week')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
