# Generated by Django 4.2.7 on 2024-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_topic_watched_by_users_studentcourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
