# Generated by Django 4.2.7 on 2024-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_questionpaper_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
