# Generated by Django 5.0.4 on 2024-04-25 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorship",
            name="student",
        ),
        migrations.RenameField(
            model_name="enrolledcourse",
            old_name="student",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="enrolledcourse",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="enrolledcourse",
            name="progress_percentage",
        ),
        migrations.AddField(
            model_name="enrolledcourse",
            name="enrolled_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="QuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField()),
                ("question_file", models.FileField(upload_to="question_papers/")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CareerOption",
        ),
        migrations.DeleteModel(
            name="Mentorship",
        ),
    ]
