# Generated by Django 5.0.4 on 2024-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_mentorship_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
