# Generated by Django 5.0.4 on 2024-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(default="Tech Courses", max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="grade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name="QuestionPaper",
        ),
    ]
