# Generated by Django 5.0.4 on 2024-04-26 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
