# Generated by Django 5.0.4 on 2024-04-27 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_delete_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EnrolledCourse",
        ),
    ]
