# Generated by Django 5.0.4 on 2024-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_auto_20240427_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertbl",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
