# Generated by Django 5.0.4 on 2024-04-27 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_usertbl_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertbl",
            name="user",
        ),
    ]
