# Generated by Django 5.0.4 on 2024-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_remove_usertbl_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="staticfiles/course_images/"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("Tech Courses", "Tech Courses"),
                    ("CBSE Courses", "CBSE Courses"),
                ],
                default="Tech Courses",
                max_length=100,
            ),
        ),
    ]
