# Generated by Django 5.0.4 on 2024-04-27 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_previousyearquestionpaper"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreviousYearQuestionPaper",
        ),
    ]
