# Generated by Django 5.0.4 on 2024-04-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_mentorship"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorship",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="mentorship",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
