# Generated by Django 5.0.4 on 2024-04-29 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_mentorship_email_mentorship_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usertbl",
            new_name="Student",
        ),
    ]
