# Generated by Django 4.1.4 on 2024-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_video_course_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="videos",
        ),
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="staticfiles/demo_videos/"
            ),
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
