# Generated by Django 4.1.4 on 2024-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_remove_course_videos_course_video_delete_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="video",
            new_name="demo_video",
        ),
        migrations.AddField(
            model_name="course",
            name="course_video",
            field=models.FileField(
                blank=True, null=True, upload_to="staticfiles/course_videos/"
            ),
        ),
    ]
